[package]
name = "communal-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "WebAssembly bindings for community detection"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
communal-core = { path = "../communal-core" }
communal-algo = { path = "../communal-algo" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = "0.6"

[lints]
workspace = true
