[package]
name = "communal-metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Evaluation metrics for community detection"
repository.workspace = true

[dependencies]
communal-core = { path = "../communal-core" }

[lints]
workspace = true
