[package]
name = "communal-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
num-traits = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
